# Generated by Django 2.0.4 on 2018-04-14 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupons',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AlterField(
            model_name='cupons',
            name='active',
            field=models.BooleanField(verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='cupons',
            name='discount',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
                verbose_name='Процент скидки'),
        ),
        migrations.AlterField(
            model_name='cupons',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='cupons',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Дата конца'),
        ),
    ]
