# Generated by Django 2.0.4 on 2018-04-14 19:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cupons', '0002_auto_20180414_2231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupons',
            new_name='Cupon',
        ),
    ]
