# Generated by Django 2.0.4 on 2018-04-15 08:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0002_auto_20180415_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='orders', to='cupons.Cupon', verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0),
                                                             django.core.validators.MaxValueValidator(100)],
                                      verbose_name='Скидка'),
        ),
    ]
